name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install dependencies
        run: npm ci

      - name: Run Deno tests
        run: deno test

      - name: Build npm package
        run: npm run build

      - name: Generate syntax files
        run: cd vscode-extension && deno run --allow-read --allow-write generate-syntaxes.ts

      - name: Package VSCode extension
        run: cd vscode-extension && npm install -g @vscode/vsce && vsce package
